### ISSUE TITLE
Automatically remove escape character

### ISSUE THREAD

**Issue by florianbouvot** [andersea/HTMLClassSuggestionsVSCode#10] opened 2017-04-11 13:01 UTC
I frequently use `\` espace character in my CSS files like this : `.u-1\/2 { width: 50% !important; }`

Is it possible to automatically remove it from suggestion list ?

**Comment by andersea** [comment] 2017-04-11 13:27
You want to remove the item entirely or just the escape character?

**Comment by florianbouvot** [comment] 2017-04-11 13:47
Juste remove the escape character to obtain this result: 

CSS: `.u-1\/2 { width: 50% !important; }`
HTML: `<div class="u-1/2">...</div>`

**Comment by andersea** [comment] 2017-04-11 17:04
Got it. I have this working in my local repo now. It will be in the next release.

**Comment by andersea** [comment] 2017-04-11 17:43
Added in 1.0.5.

**Closed as completed by andersea** 2017-04-11 17:43 UTC
Labels: enhancement

**Comment by florianbouvot** [comment] 2017-04-11 21:31
Awesome thank you 👍

First try looks good, I will work with tomorrow 😉

**Comment by florianbouvot** [comment] 2017-04-12 18:14
@andersea it works well when backslash `\` is followed by `/` slash but doesn't work in other case like this:

CSS `.ratio-16\:9 { ... }`
HTML current result `ratio-16\`
HTML desired result `ratio-16:9`

CSS `.margin\@palm { ... }`
HTML current result `margin\@palm`
HTML desired result `margin@palm`

*I follow [BEMIT](https://csswizardry.com/2015/08/bemit-taking-the-bem-naming-convention-a-step-further/) naming convention from Harry Roberts and we use it for [inuitcss](https://github.com/inuitcss)*

Is it possible?

**Comment by andersea** [comment] 2017-04-12 21:29
@florianbouvot I was careful to account for all possible escape sequences in my code, so most should work.

I can see why `\:` wouldn't work. That is caused by another part of the code that tries to figure out where the class name is in the css selector. It isn't a super simple fix, but doable.

But the `\@` works for me. Are you sure it doesn't work on your end? I have added unit tests for it and tested it manually as well, so I feel confident. Hehe.

The escape sequences that probably doesn't work should be `\[`, `\:` and `\>`.

**Comment by andersea** [comment] 2017-04-13 10:17
v1.0.6 should fix the remaining issue.

**Comment by florianbouvot** [comment] 2017-04-13 12:08
@andersea your new release fix the issue with `\:` but there are steel an issue maybe when a class name use two `\`:

<img width="487" alt="capture d ecran 2017-04-13 a 14 07 38" src="https://cloud.githubusercontent.com/assets/2061540/25004060/b395638e-2052-11e7-93c0-aa07df3cfa34.png">

**Comment by andersea** [comment] 2017-04-13 14:36
Fixed in v1.0.7.

**Comment by florianbouvot** [comment] 2017-04-13 14:44
@andersea amazing.

*I search a Coda alternative, and I like very much VS Code + your extension, thank you.*

**Comment by andersea** [comment] 2017-04-13 14:48
I appreciate the support. Thanks!
