### ISSUE TITLE
CSS Class Completion Extension not working under VSCode 1.6?

### ISSUE THREAD

**Issue by Howshall** [andersea/HTMLClassSuggestionsVSCode#6] opened 2016-10-13 19:01 UTC
Hi Anders,
Just re-installed your CSS Class Completion extension again, after having been helping Zignd with his CSS extension for a bit (which has now also stopped working fully under v1.6)
Opened that previous main templates workspace I have (with some duplicated libraries) but don't get any status bar message that your extension has even run, and no auto completion when typing within class="" attributes like before.
Could you confirm if there's any known incompatibility or breakage with VSCode 1.6 and your extension? Is it still working okay for you?
Happy to provide any logs or assistance in trying to replicate or track this down.
Thanks in advance, Alan

**Comment by Howshall** [comment] 2016-10-13 19:07
Checking on issues reported for Zignd's VSCode CSS extension there also seems to be reports of his plugin not working since VSCode 1.6 update https://github.com/Zignd/HTML-CSS-Class-Completion/issues/28

**Comment by andersea** [comment] 2016-10-14 17:04
Hmm. It seems to be working. Tested just now on 1.6.1.

![test on vsc 1 6 1](https://cloud.githubusercontent.com/assets/10992982/19395999/03b6cc18-9241-11e6-8a2b-b5e6feec3816.png)

**Comment by Howshall** [comment] 2016-10-14 17:30
Looks like now I've updated from VSCode 1.6 to just released 1.6.1 your plugin is now partially working...in that I now get the expected dropdown, however not all expected classes are being populated into it.

Not sure how many or why some are missing yet, but my main project uses BootStrap v3 as it's base and I'm not getting full range of expected 'hidden-...' classes for example that I'd expect and had access to before.

If you see my screengrab the dropdown is missing 'hidden-xs', 'hidden-sm' and more http://getbootstrap.com/css/#responsive-utilities should definitely be appearing at point of typing to 'hidd'

![partial-classes-completion](https://cloud.githubusercontent.com/assets/13105488/19396661/0847ef8c-923c-11e6-844f-80a4d36408e8.jpg)

Presume plugin wasn't previously working at all due to one of fixed bugs between v1.6 and v1.6.1? 
https://github.com/Microsoft/vscode/milestone/31?closed=1

**Comment by Howshall** [comment] 2016-10-14 17:34
On a possible related note can you remind me if I should be seeing some sort of status bar (or other) notification of when all the CSS styles for a folder have been successfully parsed/loaded?
Currently I can't see any such indications when I open any new work folder.

**Comment by andersea** [comment] 2016-10-14 17:52
There are no notifications. Excessive notifications can be an annoyance and for normal projects with few CSS files, parsing and aggregation of classes takes milliseconds, so I didn't think it would be needed.

**Comment by Howshall** [comment] 2016-10-17 13:23
If no visible messages from plugin on load then any ideas on why it wouldn't be offering me full set of linked CSS rule names as it did before? 
Any log I can look in to pull out for you to see if all rules loaded fully, or if any errors?

BTW Do agree it was a good idea to move away from top middle VSCode notify banners, which were just a pain to have to manually submit. But maybe something subtle in bottom status bar would be an enhancement to consider?

**Comment by andersea** [comment] 2016-10-20 10:26
You can get additional debug information by running the extension in debug mode. To do that you have to download the project from github and open the project folder in vscode. You can then run the extension from the debug menu. The extension outputs debug messages to the console. It will look like this when you open a html file:

![html class suggestions debug info](https://cloud.githubusercontent.com/assets/10992982/19556211/5844946c-96c0-11e6-9bc3-46a15e286899.png)

I will look into adding some unobtrusive status messages.

**Comment by andersea** [comment] 2016-10-20 12:20
I added a simple status bar message that disappears after 10 seconds. It is published in the latest version just uploaded to marketplace.

**Comment by andersea** [comment] 2016-10-20 13:35
Ok.. Here is the lowdown.. By design the current version of the aggregator ignores selectors that are inside media rules. I simply didn't take it into account that media rules had any useful selectors that the user might want to use in the html.

As a consequence I suspect this probably never worked in any version of the extension.

Here is a build which adds handling of media rules. Can you please test if it works better for you?

[html-class-suggestions-issue-6.zip](https://github.com/andersea/HTMLClassSuggestionsVSCode/files/541811/html-class-suggestions-issue-6.zip)

**Comment by Howshall** [comment] 2016-10-21 14:20
Hi @andersea, many thanks as always for your responsiveness and updates. To summarise given this thread has branched a bit (my fault! - Happy to split into multiple if/when you ever want)

1) Confirm original problem with your plugin not working under VS Code 1.6.0 appears to have been a Visual Studio Code problem/bug which was fixed rapidly in VS Code 1.6.1

2) Thank you for adding that unobtrusive status bar message, confirm I've updated to the latest marketplace version 1.0.2 and have therefore seen that new feature Enhancement :-) 

![screenshot 700](https://cloud.githubusercontent.com/assets/13105488/19601009/552fa5ac-979f-11e6-9e14-820af7a2dfbf.png)

3) Agree my report of them 'partial working' under 1.6.1 seems I just happened to pick CSS within responsive media queries when re-testing your plugin under 1.6.1. So wrongly reported it only back partially working...it's just I'd never spotted it's lack of @media CSS classes support before!

Unfortunately I haven't been able to get your attached html-class-suggestions-issue-6.zip to install on my machine. So can't yet test if your enhanced media rules version allows me auto complete of Bootstrap responsive classes like .hidden-xs and many others.

See below for screenshot of the errors I got when trying to run the html-class-suggestions-issue-6.vsix within your Zip:
![v6 installer](https://cloud.githubusercontent.com/assets/13105488/19601453/50fb407a-97a1-11e6-9565-5d653cb4eefa.jpg)

![v6 installer error log](https://cloud.githubusercontent.com/assets/13105488/19601465/5a1364a8-97a1-11e6-8ca3-e33fb9571340.jpg)

Thank you for all your efforts and responsiveness.

**Comment by andersea** [comment] 2016-10-21 15:35
Can you try the installation instructions on this page?

https://code.visualstudio.com/Docs/extensions/install-extension#_install-a-packaged-extension-vsix

**Comment by Howshall** [comment] 2016-10-21 22:06
Hi @andersea 

Good news: Using 'Install from VSIX... ' menu option within VS Code's extensions pane got that html-class-suggestions-issue-6.vsix installed fine 👍 

Bad news: I now did get to see .hidden-xs css class show up in auto complete suggestions, but was missing previous hidden and hidden-md-grid (see my screenshot in 4th comment on this thread) and was also missing additional hidden CSS class options that should have come up.

See below for screenshot of what appeared in dropdown vs doing a search for same starting .hidden CSS classes present in Bootstrap CSS by VS Code in file search results (see left side of screenshot)

![screenshot 701](https://cloud.githubusercontent.com/assets/13105488/19612940/631e8bb4-97e1-11e6-9d52-0efeafaabb7d.png)

It does however look like there's at least some interaction with how many CSS rules are in my project as looks like all expected .hidd... rules were displayed in auto complete dropdown when tested against just minimal Bootstrap only compiled https://github.com/twbs/bootstrap/releases/download/v3.3.7/bootstrap-3.3.7-dist.zip 
See proof of that working fine below:

![screenshot 702](https://cloud.githubusercontent.com/assets/13105488/19613137/8cc8a9a8-97e2-11e6-8769-b01c3db3c288.png)

Appreciate that makes it difficult for you to work out what's going on if you can't personally replicate. Let me know if you do want me to try that debug mode or any other way of providing you with more info?

I don't believe your v6 Zip included latest loaded status message display? Or at least I'm not seeing that when loading the same project folder with v6 installed, vs I did see it when latest marketplace version was installed.

**Comment by andersea** [comment] 2016-10-22 10:14
From your last post I am not quite sure if you are saying if the bug you are seeing is fixed or not. Can you please summarize what you are seeing on your end?
- Prerequisites - Which css files are contained in your project, and what sources are they from? Have you modified the css files in any way (mainly if you modified the bootstrap or other standard css files you are using)?
- Steps - What are you typing in vscode? Other things you are doing which might be relevant?
- Expectation - Which suggestions are you expecting to see? Which css file contains your expected suggestions?
- Actual - What are you actually seeing, instead of the expected result?

**Comment by andersea** [comment] 2016-10-25 19:30
I have released v1.0.3 which should be a considerable improvement. I will close this for now, also because the actual issue described in the original post is fixed and wasn't actually an issue in the extension, but in vsc itself.

If there are any specific classes that you are still not seeing, please open a new report describing the specific case.

**Closed as completed by andersea** 2016-10-25 19:30 UTC
Labels: bug
