### ISSUE TITLE
bootstrap in node_modules folder

### ISSUE THREAD

**Issue by markiianharbych** [andersea/HTMLClassSuggestionsVSCode#8] opened 2017-02-15 17:28 UTC
Hi!

I have an angular 2 project, using angular cli library. I've installed bootstrap as a nodejs module. Angular cli using it's config file and then webpack - attaches bootstrap files to my web site.

And the issue is that I cannot see any suggestions in Visual Studio Code.

Any help on this?

**Comment by andersea** [comment] 2017-02-16 22:16
Can you make an example project that reproduces this?

**Comment by andersea** [comment] 2017-03-03 18:33
Closing due to no communication.

**Closed as completed by andersea** 2017-03-03 18:33 UTC
